-- Books module for bible text quote recognition

local book_variations = {
	es = {
		-- Old Testament Books
		["Génesis"] = "Gén",
		["Gén"] = "Gén",
		["Gén."] = "Gén",
		["Éxodo"] = "Éx",
		["Éx"] = "Éx",
		["Éx."] = "Éx",
		["Levítico"] = "Lev",
		["Lev"] = "Lev",
		["Lev."] = "Lev",
		["Números"] = "Núm",
		["Núm"] = "Núm",
		["Núm."] = "Núm",
		["Deuteronomio"] = "Deut",
		["Deut"] = "Deut",
		["Deut."] = "Deut",
		["Josué"] = "Jos",
		["Jos"] = "Jos",
		["Jos."] = "Jos",
		["Jueces"] = "Jue",
		["Jue"] = "Jue",
		["Jue."] = "Jue",
		["Rut"] = "Rut",
		["Rut."] = "Rut",
		["1 Samuel"] = "1Sam",
		["1Sam"] = "1Sam",
		["1Sam."] = "1Sam",
		["2 Samuel"] = "2Sam",
		["2Sam"] = "2Sam",
		["2Sam."] = "2Sam",
		["1 Reyes"] = "1Rey",
		["1Rey"] = "1Rey",
		["1Rey."] = "1Rey",
		["2 Reyes"] = "2Rey",
		["2Rey"] = "2Rey",
		["2Rey."] = "2Rey",
		["1 Crónicas"] = "1Cró",
		["1Cró"] = "1Cró",
		["1Cró."] = "1Cró",
		["2 Crónicas"] = "2Cró",
		["2Cró"] = "2Cró",
		["2Cró."] = "2Cró",
		["Esdras"] = "Esd",
		["Esd"] = "Esd",
		["Esd."] = "Esd",
		["Nehemías"] = "Neh",
		["Neh"] = "Neh",
		["Neh."] = "Neh",
		["Ester"] = "Est",
		["Est"] = "Est",
		["Est."] = "Est",
		["Job"] = "Job",
		["Job."] = "Job",
		["Salmos"] = "Sal",
		["Salmo"] = "Sal",
		["Sal"] = "Sal",
		["Sal."] = "Sal",
		["Proverbios"] = "Prov",
		["Prov"] = "Prov",
		["Prov."] = "Prov",
		["Eclesiastés"] = "Ecl",
		["Ecl"] = "Ecl",
		["Ecl."] = "Ecl",
		["Cantares"] = "Cant",
		["Cant"] = "Cant",
		["Cant."] = "Cant",
		["Isaías"] = "Isa",
		["Isa"] = "Isa",
		["Isa."] = "Isa",
		["Jeremías"] = "Jer",
		["Jer"] = "Jer",
		["Jer."] = "Jer",
		["Lamentaciones"] = "Lam",
		["Lam"] = "Lam",
		["Lam."] = "Lam",
		["Ezequiel"] = "Ezeq",
		["Ezeq"] = "Ezeq",
		["Ezeq."] = "Ezeq",
		["Daniel"] = "Dan",
		["Dan"] = "Dan",
		["Dan."] = "Dan",
		["Oseas"] = "Ose",
		["Ose"] = "Ose",
		["Ose."] = "Ose",
		["Joel"] = "Joel",
		["Joel."] = "Joel",
		["Amós"] = "Amós",
		["Amós."] = "Amós",
		["Abdías"] = "Abd",
		["Abd"] = "Abd",
		["Abd."] = "Abd",
		["Jonás"] = "Jonás",
		["Jonás."] = "Jonás",
		["Miqueas"] = "Miqueas",
		["Miqueas."] = "Miqueas",
		["Nahúm"] = "Nah",
		["Nah"] = "Nah",
		["Nah."] = "Nah",
		["Habacuc"] = "Hab",
		["Hab"] = "Hab",
		["Hab."] = "Hab",
		["Sofonías"] = "Sof",
		["Sof"] = "Sof",
		["Sof."] = "Sof",
		["Hageo"] = "Hag",
		["Hag"] = "Hag",
		["Hag."] = "Hag",
		["Zacarías"] = "Zac",
		["Zac"] = "Zac",
		["Zac."] = "Zac",
		["Malaquías"] = "Mal",
		["Mal"] = "Mal",
		["Mal."] = "Mal",

		-- New Testament Books
		["Mateo"] = "Mat",
		["Mat"] = "Mat",
		["Mat."] = "Mat",
		["Marcos"] = "Mar",
		["Mar"] = "Mar",
		["Mar."] = "Mar",
		["Lucas"] = "Luc",
		["Luc"] = "Luc",
		["Luc."] = "Luc",
		["Juan"] = "Juan",
		["Juan."] = "Juan",
		["Hechos"] = "Hech",
		["Hech"] = "Hech",
		["Hech."] = "Hech",
		["Romanos"] = "Rom",
		["Rom"] = "Rom",
		["Rom."] = "Rom",
		["1 Corintios"] = "1Cor",
		["1Cor"] = "1Cor",
		["1Cor."] = "1Cor",
		["2 Corintios"] = "2Cor",
		["2Cor"] = "2Cor",
		["2Cor."] = "2Cor",
		["Gálatas"] = "Gál",
		["Gál"] = "Gál",
		["Gál."] = "Gál",
		["Efesios"] = "Efes",
		["Efes"] = "Efes",
		["Efes."] = "Efes",
		["Filipenses"] = "Fil",
		["Fil"] = "Fil",
		["Fil."] = "Fil",
		["Filip"] = "Fil",
		["Fili"] = "Fil",
		["Colosenses"] = "Col",
		["Col"] = "Col",
		["Col."] = "Col",
		["1 Tesalonicenses"] = "1Tes",
		["1Tes"] = "1Tes",
		["1Tes."] = "1Tes",
		["2 Tesalonicenses"] = "2Tes",
		["2Tes"] = "2Tes",
		["2Tes."] = "2Tes",
		["1 Timoteo"] = "1Tim",
		["1Tim"] = "1Tim",
		["1Tim."] = "1Tim",
		["2 Timoteo"] = "2Tim",
		["2Tim"] = "2Tim",
		["2Tim."] = "2Tim",
		["Tito"] = "Tito",
		["Tito."] = "Tito",
		["Filemón"] = "File",
		["File"] = "File",
		["File."] = "File",
		["Hebreos"] = "Heb",
		["Heb"] = "Heb",
		["Heb."] = "Heb",
		["Santiago"] = "Sant",
		["Sant"] = "Sant",
		["Sant."] = "Sant",
		["1 Pedro"] = "1Ped",
		["1Ped"] = "1Ped",
		["1Ped."] = "1Ped",
		["2 Pedro"] = "2Ped",
		["2Ped"] = "2Ped",
		["2Ped."] = "2Ped",
		["1 Juan"] = "1Juan",
		["1Juan"] = "1Juan",
		["1Juan."] = "1Juan",
		["2 Juan"] = "2Juan",
		["2Juan"] = "2Juan",
		["2Juan."] = "2Juan",
		["3 Juan"] = "3Juan",
		["3Juan"] = "3Juan",
		["3Juan."] = "3Juan",
		["Judas"] = "Jud",
		["Jud"] = "Jud",
		["Jud."] = "Jud",
		["Apocalipsis"] = "Apoc",
		["Apoc"] = "Apoc",
		["Apoc."] = "Apoc",
	},
	en = {
		-- Old Testament Books
		["Genesis"] = "Gen",
		["Gen"] = "Gen",
		["Gen."] = "Gen",
		["Exodus"] = "Ex",
		["Ex"] = "Ex",
		["Ex."] = "Ex",
		["Leviticus"] = "Lev",
		["Lev"] = "Lev",
		["Lev."] = "Lev",
		["Numbers"] = "Num",
		["Num"] = "Num",
		["Num."] = "Num",
		["Deuteronomy"] = "Deut",
		["Deut"] = "Deut",
		["Deut."] = "Deut",
		["Joshua"] = "Josh",
		["Josh"] = "Josh",
		["Josh."] = "Josh",
		["Judges"] = "Judg",
		["Judg"] = "Judg",
		["Judg."] = "Judg",
		["Ruth"] = "Ruth",
		["Ruth."] = "Ruth",
		["1 Samuel"] = "1Sam",
		["1Sam"] = "1Sam",
		["1Sam."] = "1Sam",
		["2 Samuel"] = "2Sam",
		["2Sam"] = "2Sam",
		["2Sam."] = "2Sam",
		["1 Kings"] = "1Kgs",
		["1Kgs"] = "1Kgs",
		["1Kgs."] = "1Kgs",
		["2 Kings"] = "2Kgs",
		["2Kgs"] = "2Kgs",
		["2Kgs."] = "2Kgs",
		["1 Chronicles"] = "1Chr",
		["1Chr"] = "1Chr",
		["1Chr."] = "1Chr",
		["2 Chronicles"] = "2Chr",
		["2Chr"] = "2Chr",
		["2Chr."] = "2Chr",
		["Ezra"] = "Ezra",
		["Ezra."] = "Ezra",
		["Nehemiah"] = "Neh",
		["Neh"] = "Neh",
		["Neh."] = "Neh",
		["Esther"] = "Est",
		["Est"] = "Est",
		["Est."] = "Est",
		["Job"] = "Job",
		["Job."] = "Job",
		["Psalms"] = "Ps",
		["Ps"] = "Ps",
		["Ps."] = "Ps",
		["Proverbs"] = "Prov",
		["Prov"] = "Prov",
		["Prov."] = "Prov",
		["Ecclesiastes"] = "Eccl",
		["Eccl"] = "Eccl",
		["Eccl."] = "Eccl",
		["Song of Solomon"] = "Song",
		["Song"] = "Song",
		["Song."] = "Song",
		["Isaiah"] = "Isa",
		["Isa"] = "Isa",
		["Isa."] = "Isa",
		["Is"] = "Isa",
		["Is."] = "Isa",
		["Jeremiah"] = "Jer",
		["Jer"] = "Jer",
		["Jer."] = "Jer",
		["Lamentations"] = "Lam",
		["Lam"] = "Lam",
		["Lam."] = "Lam",
		["Ezekiel"] = "Ezek",
		["Ezek"] = "Ezek",
		["Ezek."] = "Ezek",
		["Daniel"] = "Dan",
		["Dan"] = "Dan",
		["Dan."] = "Dan",
		["Hosea"] = "Hos",
		["Hos"] = "Hos",
		["Hos."] = "Hos",
		["Joel"] = "Joel",
		["Joel."] = "Joel",
		["Amos"] = "Amos",
		["Amos."] = "Amos",
		["Obadiah"] = "Obad",
		["Obad"] = "Obad",
		["Obad."] = "Obad",
		["Jonah"] = "Jon",
		["Jon"] = "Jon",
		["Jon."] = "Jon",
		["Micah"] = "Mic",
		["Mic"] = "Mic",
		["Mic."] = "Mic",
		["Nahum"] = "Nah",
		["Nah"] = "Nah",
		["Nah."] = "Nah",
		["Habakkuk"] = "Hab",
		["Hab"] = "Hab",
		["Hab."] = "Hab",
		["Zephaniah"] = "Zeph",
		["Zeph"] = "Zeph",
		["Zeph."] = "Zeph",
		["Haggai"] = "Hag",
		["Hag"] = "Hag",
		["Hag."] = "Hag",
		["Zechariah"] = "Zech",
		["Zech"] = "Zech",
		["Zech."] = "Zech",
		["Malachi"] = "Mal",
		["Mal"] = "Mal",
		["Mal."] = "Mal",

		-- New Testament Books
		["Matthew"] = "Matt",
		["Matt"] = "Matt",
		["Matt."] = "Matt",
		["Mark"] = "Mark",
		["Mark."] = "Mark",
		["Luke"] = "Luke",
		["Luke."] = "Luke",
		["John"] = "John",
		["John."] = "John",
		["Acts"] = "Acts",
		["Acts."] = "Acts",
		["Romans"] = "Rom",
		["Rom"] = "Rom",
		["Rom."] = "Rom",
		["1 Corinthians"] = "1Cor",
		["1Cor"] = "1Cor",
		["1Cor."] = "1Cor",
		["2 Corinthians"] = "2Cor",
		["2Cor"] = "2Cor",
		["2Cor."] = "2Cor",
		["Galatians"] = "Gal",
		["Gal"] = "Gal",
		["Gal."] = "Gal",
		["Ephesians"] = "Eph",
		["Eph"] = "Eph",
		["Eph."] = "Eph",
		["Philippians"] = "Phil",
		["Phil"] = "Phil",
		["Phil."] = "Phil",
		["Colossians"] = "Col",
		["Col"] = "Col",
		["Col."] = "Col",
		["1 Thessalonians"] = "1Thess",
		["1Thess"] = "1Thess",
		["1Thess."] = "1Thess",
		["2 Thessalonians"] = "2Thess",
		["2Thess"] = "2Thess",
		["2Thess."] = "2Thess",
		["1 Timothy"] = "1Tim",
		["1Tim"] = "1Tim",
		["1Tim."] = "1Tim",
		["2 Timothy"] = "2Tim",
		["2Tim"] = "2Tim",
		["2Tim."] = "2Tim",
		["Titus"] = "Titus",
		["Titus."] = "Titus",
		["Philemon"] = "Philem",
		["Philem"] = "Philem",
		["Philem."] = "Philem",
		["Hebrews"] = "Heb",
		["Heb"] = "Heb",
		["Heb."] = "Heb",
		["James"] = "Jas",
		["Jas"] = "Jas",
		["Jas."] = "Jas",
		["1 Peter"] = "1Pet",
		["1Pet"] = "1Pet",
		["1Pet."] = "1Pet",
		["2 Peter"] = "2Pet",
		["2Pet"] = "2Pet",
		["2Pet."] = "2Pet",
		["1 John"] = "1John",
		["1John"] = "1John",
		["1John."] = "1John",
		["2 John"] = "2John",
		["2John"] = "2John",
		["2John."] = "2John",
		["3 John"] = "3John",
		["3John"] = "3John",
		["3John."] = "3John",
		["Jude"] = "Jude",
		["Jude."] = "Jude",
		["Revelation"] = "Rev",
		["Rev"] = "Rev",
		["Rev."] = "Rev",
	},
}

-- Book numbers (1-66) mapped by normalized abbreviation
local book_numbers = {
	es = {
		["Gén"] = "1", ["Éx"] = "2", ["Lev"] = "3", ["Núm"] = "4", ["Deut"] = "5",
		["Jos"] = "6", ["Jue"] = "7", ["Rut"] = "8", ["1Sam"] = "9", ["2Sam"] = "10",
		["1Rey"] = "11", ["2Rey"] = "12", ["1Cró"] = "13", ["2Cró"] = "14", ["Esd"] = "15",
		["Neh"] = "16", ["Est"] = "17", ["Job"] = "18", ["Sal"] = "19", ["Prov"] = "20",
		["Ecl"] = "21", ["Cant"] = "22", ["Isa"] = "23", ["Jer"] = "24", ["Lam"] = "25",
		["Ezeq"] = "26", ["Dan"] = "27", ["Ose"] = "28", ["Joel"] = "29", ["Amós"] = "30",
		["Abd"] = "31", ["Jonás"] = "32", ["Miqueas"] = "33", ["Nah"] = "34", ["Hab"] = "35",
		["Sof"] = "36", ["Hag"] = "37", ["Zac"] = "38", ["Mal"] = "39", ["Mat"] = "40",
		["Mar"] = "41", ["Luc"] = "42", ["Juan"] = "43", ["Hech"] = "44", ["Rom"] = "45",
		["1Cor"] = "46", ["2Cor"] = "47", ["Gál"] = "48", ["Efes"] = "49", ["Fil"] = "50",
		["Col"] = "51", ["1Tes"] = "52", ["2Tes"] = "53", ["1Tim"] = "54", ["2Tim"] = "55",
		["Tito"] = "56", ["File"] = "57", ["Heb"] = "58", ["Sant"] = "59", ["1Ped"] = "60",
		["2Ped"] = "61", ["1Juan"] = "62", ["2Juan"] = "63", ["3Juan"] = "64", ["Jud"] = "65",
		["Apoc"] = "66",
	},
	en = {
		["Gen"] = "1", ["Ex"] = "2", ["Lev"] = "3", ["Num"] = "4", ["Deut"] = "5",
		["Josh"] = "6", ["Judg"] = "7", ["Ruth"] = "8", ["1Sam"] = "9", ["2Sam"] = "10",
		["1Kgs"] = "11", ["2Kgs"] = "12", ["1Chr"] = "13", ["2Chr"] = "14", ["Ezra"] = "15",
		["Neh"] = "16", ["Est"] = "17", ["Job"] = "18", ["Ps"] = "19", ["Prov"] = "20",
		["Eccl"] = "21", ["Song"] = "22", ["Isa"] = "23", ["Jer"] = "24", ["Lam"] = "25",
		["Ezek"] = "26", ["Dan"] = "27", ["Hos"] = "28", ["Joel"] = "29", ["Amos"] = "30",
		["Obad"] = "31", ["Jon"] = "32", ["Mic"] = "33", ["Nah"] = "34", ["Hab"] = "35",
		["Zeph"] = "36", ["Hag"] = "37", ["Zech"] = "38", ["Mal"] = "39", ["Matt"] = "40",
		["Mark"] = "41", ["Luke"] = "42", ["John"] = "43", ["Acts"] = "44", ["Rom"] = "45",
		["1Cor"] = "46", ["2Cor"] = "47", ["Gal"] = "48", ["Eph"] = "49", ["Phil"] = "50",
		["Col"] = "51", ["1Thess"] = "52", ["2Thess"] = "53", ["1Tim"] = "54", ["2Tim"] = "55",
		["Titus"] = "56", ["Philem"] = "57", ["Heb"] = "58", ["Jas"] = "59", ["1Pet"] = "60",
		["2Pet"] = "61", ["1John"] = "62", ["2John"] = "63", ["3John"] = "64", ["Jude"] = "65",
		["Rev"] = "66",
	},
}

local function resolve_book_name(book, language)
	if not language or not book_variations[language] then
		return nil
	end

	-- Check if the book is already a standard abbreviation
	if book_variations[language][book] then
		return book_variations[language][book]
	end

	return nil
end

local function get_book_number(book, language)
	local normalized_book = resolve_book_name(book, language) or book
	return book_numbers[language] and book_numbers[language][normalized_book] or nil
end

local function get_book_name(code, language)
	return book_numbers[language] and book_numbers[language][code] or nil
end

return {
	resolve_book_name = resolve_book_name,
	get_book_number = get_book_number,
	get_book_name = get_book_name,
	book_numbers = book_numbers,
}
